version: '3.7'
services:
  frontend-react:
    image: node:14.15-alpine
    container_name: frontend-react
    working_dir: /app
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    stdin_open: true
    command: ash -c "npm install && npm start"